#! /bin/sh

# ~/.fehbg &
# blueman-applet &
# setxkbmap -layout us,gr -option grp:alt_space_toggle &

# if [[ $(xrandr -q | grep 'HDMI-1 connected') && $(xrandr -q | grep 'eDP-1 connected')]]; then
#     echo "test 1" > ~/.setup.txt
#     ~/.screenlayout/home.sh
#     bspc monitor HDMI-1 -d 1 2 3 4 5
#     bspc monitor eDP-1 -d 6 7 8 9 10
# elif [[ $(xrandr -q | grep 'eDP-1 connected') && $(xrandr -q | grep 'eDP-3 connected')]]; then
#     echo "test 2" > ~/.setup.txt
#     ~/.screenlayout/work.sh
#     bspc monitor HDMI-1 -d 1 2 3 4 5
#     bspc monitor eDP-1 -d 6 7 8 9 10
# else
#     echo "test 3" > ~/.setup.txt
#     bspc monitor -d 1 2 3 4 5 6 7 8 9 10
# fi

# ~/.screenlayout/home.sh &
bspc monitor HDMI-1 -d 1 2 3 4 5
# ~/.screenlayout/home.sh &
# bspc monitor DP-3 -d 1 2 3 4 5
bspc monitor eDP-1 -d 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Emacs state=tiled
bspc rule -a brave-browser desktop='^1'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

#Autostart applications
sxhkd &
redshift -l 37.9637676:23.7275817 &
# picom --config $HOME/.config/picom/picom.conf &
dunst &
polybar &
